### PR TITLE
feat(integration): Add update files feature for S3 to Pinecone

### PR DESCRIPTION
**Pull request by bouyang**
Added the update feature for S3 to Pinecone. This feature will detect if the newly added document already exists in the bucket and if so, first delete the associated vectors and then add the files using the normal pipeline.

Because both the addLambda and deleteLambda use the Pinecone deletion utility, I separated it to its own file that both can use.

Because the deletion of vectors occurs much quicker than the addition of vectors (which takes time for the task to run), for now there is no validation but would be something to look into to ensure that vectors are not added before they are deleted.

### CODE REVIEW

**Comment by amirsadeghifar** [comment]
Great work Brian. One issue I'm running into is having to authenticate ECR to pull the docker image for python:

`docker: Error response from daemon: pull access denied for public.ecr.aws/sam/build-python3.9`

I think we can avoid this extra step as well as unnecessarily pulling the entire python image locally by either:
1) Using a lambda layer for dependencies
or
2) Install dependencies directly in function directory

I think using a lambda layer would be the cleaner approach.

**Comment by bouyang** [comment]
Hi Amir, thanks for the catch. Based on our discussion, it seems like the issue is coming from this part of the code:

```
 code: lambda.Code.fromAsset('lambda', {
        bundling: {
          image: lambda.Runtime.PYTHON_3_9.bundlingImage,
          command: [
            'bash', '-c',
            'pip install -r requirements.txt -t /asset-output && cp -r . /asset-output'
          ],
        },
      }),
```

I changed the Lambda codes such that we install the dependencies in the folder itself so that they should have access to those packages without having to download the requirements. This should hopefully allow us to remove the bundling component.

I will update the code with that change and also include our updated architecture that involves passing in the ingestion script via environmental variable and submit a new PR.

**Review by camachoh1 — APPROVED** [review]
Changes look good to me, thanks Brian 👍

**Comment by amirsadeghifar** [comment]
I'm getting an error about the notification options:

`Error: NotificationKeyFilter must specify prefix and/or suffix`

Seems like the notification-options object cannot be empty.

**Comment by bouyang** [comment]
I made some minor changes where we check if the prefix is specified and create the notifications with those additional options and if no prefix is specified, we create the notifications without that third optional parameter. Hopefully this should fix that bug.

The other change is uploading the vectors into a namespace based on the filename of the document. This should allow us to delete the vectors without needing to iterate through every vector in the database so it should scale in O(1) time now.

**Comment by camachoh1** [comment]
Updated Lambda Handlers and Fixed CDK Deployment Bug
- Resolved PR conflicts.
- Updated add_lambda_function and delete_lambda_function handlers to match updated file paths and directory structure.
-  Fixed bug in add_lambda_function where unverified access to 'Contents' in the response caused CDK deployment issues.

**Pull request merged**
